site_name: BAMON
site_description: Bash Daemon Monitor - A lightweight monitoring solution
site_url: https://wawrepo.github.io/bamon/
repo_url: https://github.com/WawRepo/bamon
repo_name: WawRepo/bamon
edit_uri: edit/main/docs/

theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra:
  version: "{{ version }}"
  version_info: "{{ version_info }}"

nav:
  - Home: index.md
  - Installation: installation.md
  - Uninstallation: uninstallation.md
  - Commands:
    - Commands Overview: commands/index.md
    - status: commands/status.md
    - add: commands/add.md
    - remove: commands/remove.md
    - list: commands/list.md
    - now: commands/now.md
    - start: commands/start.md
    - stop: commands/stop.md
    - restart: commands/restart.md
    - log: commands/log.md
    - performance: commands/performance.md
    - config: commands/config.md
  - Configuration: configuration.md
  - Examples: examples.md
  - Troubleshooting: troubleshooting.md

# extra:
#   version:
#     provider: mike
