name: Build and deploy documentation

on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-linkcheck
          pip install mkdocs-spellcheck

      - name: Build documentation
        run: mkdocs build

      - name: Check links
        run: |
          mkdocs-linkcheck --ignore-url "https://github.com/WawRepo/bamon" --ignore-url "https://wawrepo.github.io/bamon" || echo "Some links may be broken, but continuing..."

      - name: Spell check
        run: mkdocs-spellcheck || echo "Spell check found issues, but continuing..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
